'use client';
import { useState } from 'react';

export default function ManagementSummaryHistory() {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [reports, setReports] = useState(null);

  async function toggle() {
    if (!open && reports === null) {
      setLoading(true);
      const data = await fetch('/api/company/management-summaries').then((r) => r.json());
      setReports(data);
      setLoading(false);
    }
    setOpen((v) => !v);
  }

  return (
    <div>
      <button className="secondary" onClick={toggle}>{open ? 'Hide' : 'View'} created reports</button>
      {open && (
        loading ? <p style={{ color: 'var(--ink-500)' }}>Loading…</p> : (
          <div className="table-scroll" style={{ marginTop: 10 }}>
            <table>
              <thead><tr><th>Report Date</th><th>Generated</th><th>Generated By</th><th></th></tr></thead>
              <tbody>
                {reports.map((r) => (
                  <tr key={r.id}>
                    <td>{r.report_date || '—'}</td>
                    <td>{new Date(r.generated_at).toLocaleString()}</td>
                    <td>{r.generated_by_name || '—'}</td>
                    <td><a href={`/api/documents/${r.id}/download`}>Download</a></td>
                  </tr>
                ))}
                {!reports.length && <tr><td colSpan={4}>No Management Summary Reports generated yet.</td></tr>}
              </tbody>
            </table>
          </div>
        )
      )}
    </div>
  );
}
