'use client';
import { useState, useEffect, useRef } from 'react';

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result.split(',')[1]);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

export default function ConfigurePage() {
  const [branding, setBranding] = useState(null);
  const [loading, setLoading] = useState(true);
  const [status, setStatus] = useState(null);
  const [prefix, setPrefix] = useState('');
  const logoRef = useRef(null);
  const letterheadRef = useRef(null);

  useEffect(() => {
    fetch('/api/company/branding').then((r) => r.json()).then((d) => {
      setBranding(d);
      setPrefix(d.report_prefix || `${d.code}/ACC/AR`);
      setLoading(false);
    });
  }, []);

  async function uploadImage(kind, file) {
    if (!file) return;
    if (!file.type.startsWith('image/')) {
      setStatus({ kind: 'error', text: `That's a ${file.type || 'non-image'} file. Please upload a PNG or JPG image — if your letterhead is a PDF or Word document, take a screenshot or export it as an image first.` });
      return;
    }
    if (file.size > 2 * 1024 * 1024) { setStatus({ kind: 'error', text: 'Please use an image under 2MB.' }); return; }
    setStatus({ kind: 'info', text: `Uploading ${kind}…` });
    const base64 = await fileToBase64(file);
    const body = kind === 'logo'
      ? { logo_base64: base64, logo_mime: file.type }
      : { letterhead_base64: base64, letterhead_mime: file.type };
    const res = await fetch('/api/company/branding', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    if (res.ok) {
      const updated = await fetch('/api/company/branding').then((r) => r.json());
      setBranding(updated);
      setStatus({ kind: 'success', text: `${kind === 'logo' ? 'Logo' : 'Letterhead'} updated.` });
    } else {
      setStatus({ kind: 'error', text: 'Upload failed.' });
    }
  }

  async function savePrefix() {
    setStatus({ kind: 'info', text: 'Saving…' });
    const res = await fetch('/api/company/branding', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ report_prefix: prefix }) });
    setStatus(res.ok ? { kind: 'success', text: 'Reference number prefix saved.' } : { kind: 'error', text: 'Save failed.' });
  }

  if (loading) return <div><h2>Configure</h2><p>Loading…</p></div>;

  const nextYear = new Date().getFullYear();

  return (
    <div>
      <h2>Configure — {branding.name}</h2>
      <p style={{ color: 'var(--ink-500)' }}>Company branding and document numbering for reports generated by AR Suite.</p>

      {status && <p style={{ color: status.kind === 'error' ? 'var(--amber)' : status.kind === 'success' ? 'var(--green-700)' : 'var(--ink-500)' }}>{status.text}</p>}

      <div className="card">
        <h4>Company Logo</h4>
        <p style={{ fontSize: 13, color: 'var(--ink-500)' }}>Used as a small mark on reports. PNG or JPG, ideally square, under 2MB.</p>
        {branding.logo_base64 && (
          <img src={`data:${branding.logo_mime};base64,${branding.logo_base64}`} alt="Company logo" style={{ maxHeight: 80, marginBottom: 10, display: 'block' }} />
        )}
        <input ref={logoRef} type="file" accept="image/png,image/jpeg" onChange={(e) => uploadImage('logo', e.target.files[0])} />
      </div>

      <div className="card">
        <h4>Company Letterhead</h4>
        <p style={{ fontSize: 13, color: 'var(--ink-500)' }}>
          A full-width header image (your official letterhead top banner) used on the Management Summary Report.
          PNG or JPG, landscape orientation, under 2MB.
        </p>
        {branding.letterhead_base64 && (
          <img src={`data:${branding.letterhead_mime};base64,${branding.letterhead_base64}`} alt="Company letterhead" style={{ maxWidth: '100%', maxHeight: 160, marginBottom: 10, display: 'block', border: '1px solid var(--ink-100)' }} />
        )}
        <input ref={letterheadRef} type="file" accept="image/png,image/jpeg" onChange={(e) => uploadImage('letterhead', e.target.files[0])} />
      </div>

      <div className="card">
        <h4>Report Reference Number</h4>
        <p style={{ fontSize: 13, color: 'var(--ink-500)' }}>
          Every Management Summary Report gets a unique reference number: <code>{prefix || `${branding.code}/ACC/AR`}/{nextYear}/001</code>, incrementing per year.
        </p>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <input value={prefix} onChange={(e) => setPrefix(e.target.value)} placeholder={`${branding.code}/ACC/AR`} style={{ width: 260 }} />
          <button onClick={savePrefix}>Save</button>
        </div>
      </div>
    </div>
  );
}
